echo "=== BEM Chatting Platform Demo ==="
echo ""
echo "✓ Development server is running on http://localhost:3000"
echo ""
echo "=== Demo Users ==="
echo "1. Email: test@example.com, Password: password123"
echo "2. Email: bem@example.com, Password: password123"
echo ""
echo "=== Application Features ==="
echo "✓ Homepage with attractive design"
echo "✓ User registration and authentication"
echo "✓ Real-time messaging interface"
echo "✓ MongoDB integration"
echo "✓ JWT-based authentication"
echo "✓ Responsive design"
echo ""
echo "=== Access Links ==="
echo "Homepage: http://localhost:3000"
echo "Login: http://localhost:3000/login"
echo "Register: http://localhost:3000/register"
echo "Messages: http://localhost:3000/messages"
echo ""
echo "=== All Levels Completed! ==="
echo "✅ Level 1: Eye-catching Homepage"
echo "✅ Level 2: Messaging with React Hooks"
echo "✅ Level 3: Backend with MongoDB and Auth"
echo "✅ Level 4: Frontend-Backend Integration"
echo ""
echo "Happy chatting!"
